apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fnp-app
  name: fnp-app
  namespace: default
spec:
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: fnp-app
  template:
    metadata:
      labels:
        app: fnp-app
    spec:
      containers:
        - image: fnp-app:v1
          imagePullPolicy: IfNotPresent
          name: fnp-app
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /root/k8s
              name: k8s
            - mountPath: /opt/dpdk
              name: dpdk
              readOnly: true
            - mountPath: /var/run/dpdk
              name: var-dpdk
            - mountPath: /dev/hugepages
              name: hugepages
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - hostPath:
            path: /root/fnp/k8s
            type: Directory
          name: k8s
        - hostPath:
            path: /opt/dpdk
            type: Directory
          name: dpdk
        - hostPath:
            path: /var/run/dpdk
            type: DirectoryOrCreate
          name: var-dpdk
        - hostPath:
            path: /dev/hugepages
            type: Directory
          name: hugepages
