#ifndef CC_INTERNAL_H
#define CC_INTERNAL_H


#define PICOQUIC_MAX_PACKET_SIZE 1536
#define PICOQUIC_CWIN_INITIAL (10 * PICOQUIC_MAX_PACKET_SIZE)
#define PICOQUIC_CWIN_MINIMUM (2 * PICOQUIC_MAX_PACKET_SIZE)

#endif //CC_INTERNAL_H
