[dpdk]
lcore_list=2,3,4,5
whitelists=0000:03:00.0
iova_mode=pa

#main_lcore must in lcore_list
;main_lcore=5
lcore1=3
lcore2=4

#channel=4
no_huge=0
numa_on=1

# Promiscuous mode of nic, defualt: enabled.
promiscuous=1

[port0]
ipaddr = 192.168.11.66
netmask = 255.255.255.0
gateway = 192.168.11.2
