dpdk:
  mbuf_pool_size: 8191
  argv:
    - "-l 2,3,4"                            # 指定DPDK使用的核心
    - "--proc-type=primary"                 # dpdk进程类型, 取值：primary or secondary or auto
#    - "--main-lcore=2"                      # 指定主核，必须出现在lcores中
#    - "--iova-mode=pa"                      # iova模式, 取值：pa or va
#    - "--base-virtaddr=0x000000000000"      # 虚拟基地址
#    - "-a 0000:03:00.0"                     # 白名单, -a, --allow，该参数可以出现多次
#    - "-n 4"                                # 内存通道数
#    - "--no-huge"                           # 不使用hugepage
#    - "--no-pci"                            # 不使用pci
worker1: 3       #for rx and tx
worker2: 4       #协议栈处理
ports:
  - ip: "192.168.11.222"
    ip_mask: "255.255.255.0"
    gateway: "192.168.11.2"
    promiscuous: true
    nb_rx_queue: 1            #网卡的接收队列数
    nb_rx_desc: 2048          #接收描述符数
    nb_tx_queue: 1            #网卡的发送队列数
    nb_tx_desc: 2048          #发送描述符数
    rx_ring_size: 10240       #接收环形队列大小
    tx_ring_size: 10240       #发送环形队列大小
    rx_mbuf_pool_size: 8191   #网卡的接收mbuf池大小
